# Homework 2

### Due Date: Friday, March 20

### Policy Gradient

In this assignment, we will implement vanilla policy gradient algorithm (REINFORCE) covered in the lecture. You will work on i) a function approximator, ii) computing action, iii) collecting samples, iV) training the agent, V) plotting the resutls. 


***Complete the missing operations and test your implemented algorithm on the Gym environment.***

***Software requirements:***
- Python >= 3.6
- Tensorflow version <= 1.15.3 (1.X version)
- OpenAI Gym

- Training the agent (policy) can take long time. It is recomended to start solving the problems earlier.

- Save any plots you generated in this notebook. The grade will be given based on the plots you showed.



Make sure the packages you installed meet the requirements.

In [2]:
import tensorflow as tf
tf.__version__

'1.15.3'

In [ ]:
pip install ipdb

In [3]:
import gym
gym.__version__

'0.18.0'

## 1.1 Tensorflow Implementation

We will be implementing policy gradient algorithm using Tensorflow 1.X., which simply updates the parameters of policy from obtaining gradient estimates. The core of policy gradient is to design a function approximator, computing actions, collecting samples, and training the policy. In the below cell, you are encouraged to fill in the components that are missing. ***Your tasks*** are 

1. Complete the 'create_model' method to output the mean value for diagonal Guassian policy. Covariance is already defined in the model, so focus on creating neural network model.

2. Complete the 'action_op' method to calculate and return the actions for diagonal Gaussian policy. The applied action should be $\pi(s) = \pi_{\text{mean}}(s) + exp(logstd) * \mathcal{N}(0,1)$

***Hints***:
- Some useful tensorflow classes and methods include: 'tf.exp', 'tf.random_normal'



***IF you are using MAC, please run below box***

In [ ]:
import os
# MAC user only
os.environ['KMP_DUPLICATE_LIB_OK']='True'

In [2]:
import tensorflow as tf
import numpy as np
import os
import ipdb


class PolicyOpt(object):

    def __init__(self, env, linear=False, stochastic=True, hidden_size=32, nonlinearity=tf.nn.relu):
        """Instantiate the policy iteration class.

        This initializes the policy optimization with a set of trainable 
        parameters, and creates a tensorflow session.

        Attributes
        ----------
        env : gym.Env
            the environment that the policy will be trained on
        linear : bool, optional
            specifies whether to use a linear or neural network 
            policy, defaults to False (i.e. Fully-Connected-Neural-Network)
        stochastic : bool, optional
            specifies whether to use a stochastic or deterministic 
            policy, defaults to True
        hidden_size : list of int, optional
            list of hidden layers, with each value corresponding 
            to the number of nodes in that layer 
        nonlinearity : tf.nn.*
            activation nonlinearity
        """
        
        # clear computation graph
        tf.reset_default_graph()
        
        # set a random seed
        tf.set_random_seed(1234)
        
        # start a tensorflow session
        self.sess = tf.Session()
        
        # environment to train on
        self.env = env
        
        # number of elements in the action space
        self.ac_dim = env.action_space.shape[0]
        
        # number of elements in the observation space
        self.obs_dim = env.observation_space.shape[0]

        # actions placeholder
        self.a_t_ph = tf.placeholder(dtype=tf.float32, 
                                     shape=[None, self.ac_dim])
        # state placeholder
        self.s_t_ph = tf.placeholder(dtype=tf.float32, 
                                     shape=[None, self.obs_dim])
        # expected reward placeholder
        self.rew_ph = tf.placeholder(dtype=tf.float32, 
                                     shape=[None])

        # specifies whether the policy is stochastic
        self.stochastic = stochastic

        # policy that the agent executes during training/testing
        self.policy = self.create_model(
            args={
                "num_actions": self.ac_dim,
                "hidden_size": hidden_size,
                "linear": linear,
                "nonlinearity": nonlinearity,
                "stochastic": stochastic,
                "scope": "policy",
            }
        )
        
        # define symbolic action
        self.symbolic_action = self.action_op()

        # initialize all variables
        self.sess.run(tf.global_variables_initializer())

        # create saver to save model variables
        self.saver = tf.train.Saver()

    def create_model(self, args):
        
        
        """Create a model for your policy or other components.

        Parameters
        ----------
        args : dict
            model-specific arguments, with keys:
              - "stochastic": True by default
              - "hidden_size": Number of neurons in hidden layer
              - "num_actions" number of output actions
              - "scope": scope of the model

        Returns
        -------
        tf.Variable
            mean actions of the policy
        tf.Variable 
            logstd of the policy actions
        """

#################### Build Your Neural Network Here! ####################  
        '''
        input_size=self.obs_dim
        hidden_size= args["hidden_size"]
        output_size= args["num_actions"] 
        weights_0 = tf.Variable(tf.random_normal([self.obs_dim , hidden_size]))
        bias_0 = tf.Variable(tf.random_normal([hidden_size]))
        weights_1 = tf.Variable(tf.random_normal([hidden_size,hidden_size]))
        bias_1 = tf.Variable(tf.random_normal([hidden_size]))
        weights_2 = tf.Variable(tf.random_normal([hidden_size,output_size]))
        bias_2 = tf.Variable(tf.random_normal([output_size]))
        hidden_layer1= tf.nn.relu(tf.add(tf.matmul( self.s_t_ph , weights_0 ) , bias_0))
        
        hidden_layer2 =tf.nn.relu(tf.add(tf.matmul( hidden_layer1 , weights_1 ) , bias_1))
        
        output_mean = tf.add(tf.matmul( hidden_layer2 , weights_2), bias_2)
        '''
        input_size=self.obs_dim
        hidden_size= args["hidden_size"]
        output_size= args["num_actions"]
        layer_1 = tf.layers.dense(self.s_t_ph, hidden_size, activation=tf.nn.relu)
        layer_2 = tf.layers.dense(layer_1, hidden_size, activation=tf.nn.relu)
        output_mean = tf.layers.dense(layer_2, output_size)
       
        
        
        
        
    
    
    
    
##########################################################################        

        if args["stochastic"]:
            output_logstd =  tf.get_variable(name="action_logstd",shape=[self.ac_dim],trainable=True)
        else:
            output_logstd = None

        return output_mean, output_logstd
    
    def action_op(self):
        """
        Create a symbolic expression that will be used to compute actions from observations.

        When the policy is stochastic, the action follows 

            a_t = output_mean + exp(output_logstd) * z; z ~ N(0,1)
        """
        if self.stochastic:
            output_mean, output_logstd = self.policy

            #################### Implement a stochastic policy here ####################        
            # Implement a stochastic version of computing actions.       #
            #                                                            #
            # The action in a stochastic policy represented by           #
            # a diagonal Gaussian distribution with mean "M" and log     #
            # standard deviation "logstd" is computed as follows:        #
            #                                                            #
            #     a = M + exp(logstd) * z                                #
            #                                                            #
            # where z is a random normal value, i.e. z ~ N(0,1)          #
            #                                                            #
            # In order to generate numbers from a normal distribution,   #
            # use the `tf.random_normal` function.                       #
            ############################################################################ 
            symbolic_action = output_mean+tf.math.exp(output_logstd)*tf.random_normal(shape=[self.ac_dim])
            
        else:
            symbolic_action, _ = self.policy
        
        return symbolic_action

    def compute_action(self, obs):
        """Returns a list of actions for a given observation.

        Parameters
        ----------
        obs : np.ndarray
            observations

        Returns
        -------
        np.ndarray
            actions by the policy for a given observation
        """
        return self.sess.run(self.symbolic_action,feed_dict={self.s_t_ph: obs})

    def rollout(self, s_mean=None, s_std=None):
        """Collect samples from one rollout of the policy.

        Returns
        -------
        dict
            dictionary containing trajectory information for the rollout,
            specifically containing keys for "state", "action", "next_state", "reward", and "done"
        """
        states = []
        next_states = []
        actions = []
        rewards = []
        dones = []

        # start a new rollout by re-setting the environment and collecting the initial state
        state =  self.env.reset()

        steps = 0
        while True:
            steps += 1

            # compute the action given the state
            if s_mean is not None and s_std is not None:
                action = self.compute_action([(state - s_mean) / s_std])
            else:
                action = self.compute_action([state])
            action = action[0]

            # advance the environment once and collect the next state, reward, done, and info parameters from the environment
            next_state, reward, done, info =  self.env.step(action)

            # add to the samples list
            states.append(state)
            actions.append(action)
            next_states.append(next_state)
            rewards.append(reward)
            dones.append(done)

            state = next_state

            # if the environment returns a True for the done parameter,
            # end the rollout before the time horizon is met
            if done or steps > env._max_episode_steps:
                break

        # create the output trajectory
        trajectory = {"state": np.array(states, dtype=np.float32),
                      "reward": np.array(rewards, dtype=np.float32),
                      "action": np.array(actions, dtype=np.float32),
                      "next_state": np.array(next_states, dtype=np.float32),
                      "done": np.array(dones, dtype=np.float32)}

        return trajectory

    def train(self, args):
        """Abstract training method.

        This method will be filled in by algorithm-specific
        training operations in subsequent problems.

        Parameters
        ----------
        args : dict
            algorithm-specific hyperparameters
        """
        raise NotImplementedError



## 1.2 Tensorflow Interpretation

In order to test your implementation of the **stochastic policy**, run the below cell. The task is to interpret the code you implemented in previous section. If you implement correctly, you can see the value_1 and value_2.

***Question: How do you interpret value_1 and value_2 below cell?***


In [3]:
import gym
TEST_ENV = gym.make("Pendulum-v0")

alg = PolicyOpt(TEST_ENV, linear=False)
input_1 = [[0, 1, 2]]
value_1 = alg.sess.run(alg.policy[0], feed_dict={alg.s_t_ph: input_1})
value_2 = alg.compute_action(input_1)

Instructions for updating:
Use keras.layers.Dense instead.
Instructions for updating:
Please use `layer.__call__` method instead.


In [4]:
value_1


array([[0.18702136]], dtype=float32)

Answer:

In [5]:
value_2

array([[-0.05820368]], dtype=float32)

Answer:

In [6]:
print(self.ac_dim)  
print(env.action_space)

NameError: name 'self' is not defined

## 1.3 Implement Policy Gradient

In this section, we will implement REINFORCE algorithm presented in the lecture. As a review, the objective is optimize the parameters $\theta$ of some policy $\pi_\theta$ so that the expected return

\begin{equation}
J(\theta) = \mathbb{E} \bigg\{ \sum_{t=0}^T \gamma^t r(s_{t},a_{t}) \bigg\}
\end{equation}

is optimized. In this algorithm, this is done by calculating the gradient $\nabla_\theta J$ and applying a gradient descent method to find a better policy.

\begin{equation}
\theta ' = \theta + \alpha \nabla_\theta J(\theta)
\end{equation}

In the lecture, we derive how we compute $\nabla_{\theta} J(\theta)$. We can rewrite our policy gradient as:

\begin{equation}
\nabla_\theta J (\theta) \approx \frac{1}{N} \sum_{i=0}^{N} \bigg( \sum_{t=0}^{T} \nabla_\theta \log \pi_\theta (a_{it} | s_{it}) \bigg) \bigg( \sum_{t=0}^T \gamma^{t}r_i(t) \bigg)
\end{equation}

Finally, taking into account the causality principle discussed in class, we are able to simplifiy the gradient estimate such as:

\begin{equation}
\nabla_\theta J (\theta) \approx \frac{1}{N} \sum_{i=0}^{N} \sum_{t=0}^{T} \nabla_\theta \log \pi_\theta (a_{it} | s_{it}) \sum_{t'=t}^T \gamma^{t'-t}r_i(t')
\end{equation}

You will be implementing final expression in this assignment!



The process of REINFOCE algorithm follows:

1. Collect samples from current policy $\pi_\theta(s)$ by executing rollouts of the environment.
2. Calculate an estimate for the expected return at state $s_t$. 
3. Compute the log-likelihood of each action that was performed by the policy at every given step.
4. Estimate the gradient and update the parameters of policy using gradient-based technique.
5. Repeat steps 1-4 for a number of training iterations.

***Your task*** is to fill out the skeleton code for REINFORCE algorithm,

1. Complete the 'log_likelihoods' method to compute gradient of policy, $\nabla_{\theta}\pi_{\theta}$ for diagonal Guassian policy. 

2. Complete the 'compute_expected_return' method to calculate the reward-to-go, $\sum_{t^{\prime}=t}^{T}$. 



In [11]:

import tensorflow as tf
import numpy as np
import time
import tensorflow_probability as tfp
import tensorflow_probability as tfp

class REINFORCE(PolicyOpt):

    def train(self, num_iterations=1000, steps_per_iteration=1000, learning_rate=int(1e-4), gamma=0.95, 
              **kwargs):
        """Perform the REINFORE training operation.

        Parameters
        ----------
        num_iterations : int
            number of training iterations
        steps_per_iteration : int
            number of individual samples collected every training iteration
        learning_rate : float
            optimizer learning rate
        gamma : float
            discount rate
        kwargs : dict
            additional arguments

        Returns
        -------
        list of float
            average return per iteration
        """
        # set the discount as an attribute
        self.gamma = gamma
        
        # set the learning rate as an attribute
        self.learning_rate = learning_rate

        # create a symbolic expression to compute the log-likelihoods 
        log_likelihoods = self.log_likelihoods()

        # create a symbolic expression for updating the parameters of your policy
        self.opt, self.opt_baseline = self.define_updates(log_likelihoods)
        
        # initialize all variables
        self.sess.run(tf.global_variables_initializer())


        # average return per training iteration
        ret_per_iteration = []
        
        samples = []
        for i in range(num_iterations):
            
            # collect samples from the current policy
            samples.clear()
            steps_so_far = 0
            while steps_so_far < steps_per_iteration:
                new_samples = self.rollout()
                steps_so_far += new_samples["action"].shape[0]
                samples.append(new_samples)

            # compute the expected returns
            v_s = self.compute_expected_return(samples)

            # compute and apply the gradients
            self.call_updates(log_likelihoods, samples, v_s, **kwargs)

            # compute the average cumulative return per iteration
            average_rew = np.mean([sum(s["reward"]) for s in samples])

            # display iteration statistics
            print("Iteration {} return: {}".format(i, average_rew))
            ret_per_iteration.append(average_rew)

        return ret_per_iteration

    def log_likelihoods(self):
        """Create a tensorflow operation that computes the log-likelihood 
        of each performed action.
        """
        
        output_mean, output_logstd = self.policy

        ##############################################################
        # Create a tf operation to compute the log-likelihood of     #
        # each action that was performed by the policy               #
        #                                                            #
        # The log likelihood in the continuous case where the policy #
        # is expressed by a multivariate gaussian can be computing   #
        # using the tensorflow object:                               #
        #                                                            #
        #    p = tfp.distributions.MultivariateNormalDiag(           #
        #        loc=...,                                            #
        #        scale_diag=...,                                     #
        #    )                                                       #
        #                                                            #
        # This method takes as input a mean (loc) and standard       #
        # deviation (scale_diag), and then can be used to compute    #
        # the log-likelihood of a variable as follows:               #
        #                                                            #
        #    log_likelihoods = p.log_prob(...)                       #
        #                                                            #
        # For this operation, you will want to use placeholders      #
        # created in the __init__ method of problem 1.               #
        ##############################################################

        p = tfp.distributions.MultivariateNormalDiag(loc=output_mean,scale_diag=tf.math.exp(output_logstd))
        log_likelihoods = p.log_prob(self.a_t_ph)  #check this also tried--> self.symbolic_action or self.a_t_ph

        return log_likelihoods

    def compute_expected_return(self, samples):
        """Compute the expected return from a given starting state.
        This is done by using the reward-to-go method.

        Parameters
        ----------
        rewards : list of list of float
            a list of N trajectories, with each trajectory contain T 
            returns values (one for each step in the trajectory)

        Returns
        -------
        list of float, or np.ndarray
            expected returns for each step in each trajectory
        """
        rewards = [s["reward"] for s in samples]

        ##############################################################
        # Estimate the expected return from any given starting state #
        # using the reward-to-go method.                             #
        #                                                            #
        # Using this method, the reward is estimated at every step   #
        # of the trajectory as follows:                              #
        #                                                            #
        #   r = sum_{t'=t}^T gamma^(t'-t) * r_{t'}                   #
        #                                                            #
        # where T is the time horizon at t is the index of the       #
        # current reward in the trajectory. For example, for a given #
        # set of rewards r = [1,1,1,1] and discount rate gamma = 1,  #
        # the expected reward-to-go would be:                        #
        #                                                            #
        #   v_s = [4, 3, 2, 1]                                       #
        #                                                            #
        # You will be able to test this in one of the cells below!   #
        ##############################################################
        v_s=[]
        for r in rewards:
            v_z=np.zeros_like(r)
            for t in range(len(r)):
                for w in range(len(r)):
                    if t<=w:
                        v_z[t]+=r[w]
                v_s.append(v_z[t])              
        return v_s
        

    def define_updates(self, log_likelihoods):
        """Create a tensorflow operation to update the parameters of 
        your policy.

        Parameters
        ----------
        log_likelihoods : tf.Operation
            the symbolic expression you created to estimate the log 
            likelihood of a set of actions

        Returns
        -------
        tf.Operation
            a tensorflow operation for computing and applying the 
            gradients to the parameters of the policy
        None
            the second component is used in problem 2.b, please ignore 
            for this problem
        """

        loss = - tf.reduce_mean(tf.multiply(log_likelihoods, self.rew_ph))
        opt = tf.train.AdamOptimizer(self.learning_rate).minimize(loss)

        return opt, None

    def call_updates(self, log_likelihoods, samples, v_s, **kwargs):
        """Apply the gradient update methods in a tensorflow session.

        Parameters
        ----------
        log_likelihoods: tf.Operation
            the symbolic expression you created to estimate the log 
            likelihood of a set of actions
        samples : list of dict
            a list of N trajectories, with each trajectory containing 
            a dictionary of trajectory data (see self.rollout)
        v_s : list of float, or np.ndarray
            the estimated expected returns from your
            `comput_expected_return` function 
        kwargs : dict
            additional arguments (used in question 3)
        """
        # concatenate the states
        states = np.concatenate([s["state"] for s in samples])

        # concatenate the actions
        actions = np.concatenate([s["action"] for s in samples])

        # execute the optimization step
        self.sess.run(self.opt, feed_dict={self.s_t_ph: states,
                                           self.a_t_ph: actions,
                                           self.rew_ph: v_s})

ModuleNotFoundError: No module named 'tensorflow_probability'

Check your 'log_likelihoods' method by running below cell:

In [12]:
alg = REINFORCE(TEST_ENV, stochastic=True)

log_likelihoods = alg.log_likelihoods()

# collect a sample output for a given input state
input_s = [[0, 0, 0], [0, 1, 2], [1, 2, 3]]
input_a = [[0], [1], [2]]

# Check
computed = alg.sess.run(log_likelihoods, feed_dict={alg.a_t_ph: input_a, alg.s_t_ph: input_s})

NameError: name 'REINFORCE' is not defined

Test your 'compute_expected_return' by running below cell:

In [14]:
# 1. Test the non-normalized case
alg = REINFORCE(TEST_ENV, stochastic=True)
alg.gamma = 1.0
    
input_1 = [{"reward": [1, 1, 1, 1]},
           {"reward": [1, 1, 1, 1]}]
vs_1 = alg.compute_expected_return(samples=input_1)
ans_1 = np.array([4, 3, 2, 1, 4, 3, 2, 1])

if np.linalg.norm(vs_1 - ans_1) < 1e-3:
    print('Great job!')
else:
    print('Check your implementation (compute_expected_return)')

    

NameError: name 'REINFORCE' is not defined

## 1.4 Testing your algorithm

When you are ready, test your policy gradient algorithms on the *Pendulum-v0* environment in the cell below. *Pendulum-v0* environment is similar to *off-shore wind power*, the goal here is to maintain the Pendulum is upright using control input. The best policy should get around -200 scores. ***Your task*** is to run your REINFORCE algorithm and plot the result!


In [15]:
# set this number as 1 for testing your algorithm, and 3 for plotting
NUM_TRIALS = 3

# ===========================================================================
# Do not modify below line
# ===========================================================================

# we will test the algorithms on the Pendulum-v0 gym environment
import gym
env = gym.make("Pendulum-v0")

# train on the REINFORCE algorithm
import numpy as np
r = []
for i in range(NUM_TRIALS):
    print("\n==== Training Run {} ====".format(i))
    alg = REINFORCE(env, stochastic=True)
    res = alg.train(learning_rate=0.005, gamma=0.95, num_iterations=500, steps_per_iteration=15000)
    r.append(np.array(res))
    alg = None

# save results
np.savetxt("InvertedPendulum_results.csv", np.array(r), delimiter=",")

def render(self, mode='human'):
        if self.viewer is None:
            from gym.envs.classic_control import rendering
            self.viewer = rendering.Viewer(500, 500)
            self.viewer.set_bounds(-2.2, 2.2, -2.2, 2.2)
            rod = rendering.make_capsule(1, .2)
            rod.set_color(.8, .3, .3)
            self.pole_transform = rendering.Transform()
            rod.add_attr(self.pole_transform)
            self.viewer.add_geom(rod)
            axle = rendering.make_circle(.05)
            axle.set_color(0, 0, 0)
            self.viewer.add_geom(axle)
            fname = path.join(path.dirname(__file__), "assets/clockwise.png")
            self.img = rendering.Image(fname, 1., 1.)
            self.imgtrans = rendering.Transform()
            self.img.add_attr(self.imgtrans)

        self.viewer.add_onetime(self.img)
        self.pole_transform.set_rotation(self.state[0] + np.pi / 2)
        if self.last_u:
            self.imgtrans.scale = (-self.last_u / 2, np.abs(self.last_u) / 2)

        return self.viewer.render(return_rgb_array=mode == 'rgb_array')


==== Training Run 0 ====


NameError: name 'REINFORCE' is not defined

In [ ]:
import gym
env = gym.make("Pendulum-v0")
for i_episode in range(1000):
    observation = env.reset()
    for t in range(10000):
        env.render()
        print(observation)
        action=alg.compute_action(observation.reshape(1,3))
        print(action)
        observation, reward, done, info=env.step(action)
        if done:
            print("episode finished after{} timesteps".format(t+1))
            break
env.close



[-0.89490748  0.44625173  0.52276955]
[[-0.15607424]]
[[-0.91273373]
 [ 0.40855488]
 [ 0.83404726]]
[[-0.91912967]]
[[-0.9320593]
 [ 0.3623058]
 [ 1.0025939]]
[[2.35916]]
[[-0.957663  ]
 [ 0.28789163]
 [ 1.5743229 ]]
[[1.6052735]]
[[-0.9819148 ]
 [ 0.18932335]
 [ 2.0310326 ]]
[[-2.2990305]]
[[-0.99531645]
 [ 0.09667049]
 [ 1.8730251 ]]
[[4.1905327]]
[[-0.99988055]
 [-0.015454  ]
 [ 2.2455277 ]]
[[-0.59435296]]
[[-0.99248254]
 [-0.12238626]
 [ 2.144784  ]]
[[2.7757964]]
[[-0.97125626]
 [-0.23803642]
 [ 2.3529944 ]]
[[2.87871]]
[[-0.9344564 ]
 [-0.35607752]
 [ 2.474467  ]]
[[-0.6161399]]
[[-0.89165145]
 [-0.4527225 ]
 [ 2.114988  ]]
[[-1.9344916]]
[[-0.85560393]
 [-0.51763105]
 [ 1.4852724 ]]
[[2.992885]]
[[-0.8173891 ]
 [-0.57608604]
 [ 1.3970491 ]]
[[2.1057305]]
[[-0.779342  ]
 [-0.62659883]
 [ 1.2649845 ]]
[[0.66044974]]
[[-0.75056046]
 [-0.66080177]
 [ 0.8941028 ]]
[[-2.4198895]]
[[-0.7472969 ]
 [-0.6644903 ]
 [ 0.09850156]]
[[0.9565785]]
[[-0.75575346]
 [-0.65485626]
 [-0.2563794 ]]

[[-0.6388878]]
[[ 0.23529737]
 [-0.9719234 ]
 [ 1.4517694 ]]
[[-1.598219]]
[[ 0.25870293]
 [-0.9659569 ]
 [ 0.48309392]]
[[0.3370178]]
[[ 0.24947508]
 [-0.9683812 ]
 [-0.19082117]]
[[-0.45750487]]
[[ 0.20146298]
 [-0.9794961 ]
 [-0.9857328 ]]
[[0.2907179]]
[[ 0.11873304]
 [-0.99292624]
 [-1.6767472 ]]
[[1.4773194]]
[[ 0.00902165]
 [-0.9999593 ]
 [-2.199844  ]]
[[2.6446762]]
[[-0.1231554]
 [-0.9923874]
 [-2.6498134]]
[[-1.8627588]]
[[-0.30233812]
 [-0.95320076]
 [-3.6735177 ]]
[[-2.0766673]]
[[-0.515478 ]
 [-0.8569028]
 [-4.6884184]]
[[1.3467833]]
[[-0.7159748 ]
 [-0.69812614]
 [-5.129078  ]]
[[-0.41491225]]
[[-0.883726  ]
 [-0.46800464]
 [-5.7149096 ]]
[[0.6816294]]
[[-0.9822211]
 [-0.1877276]
 [-5.963669 ]]
[[0.15683976]]
[[-0.99337196]
 [ 0.11494414]
 [-6.080939  ]]
[[0.2691347]]
[[-0.91595423]
 [ 0.4012827 ]
 [-5.954361  ]]
[[-2.7294614]]
[[-0.75797933]
 [ 0.6522786 ]
 [-5.953399  ]]
[[-2.8281546]]
[[-0.54131496]
 [ 0.84081995]
 [-5.76419   ]]
[[-0.06515142]]
[[-0.30965742]
 [ 0.950

[[1.5990212]]
[[0.9860454]
 [0.1664765]
 [4.279217 ]]
[[-2.662684]]
[[0.9314354]
 [0.3639067]
 [4.104074 ]]
[[-1.8667493]]
[[0.8379346]
 [0.5457706]
 [4.0969915]]
[[-4.6527243]]
[[0.70553064]
 [0.7086794 ]
 [4.2063193 ]]
[[-0.09789586]]
[[0.52013946]
 [0.85408133]
 [4.7231445 ]]
[[6.289461]]
[[0.26077873]
 [0.9653986 ]
 [5.663706  ]]
[[-6.980069]]
[[-0.04054768]
 [ 0.9991776 ]
 [ 6.0877547 ]]
[[2.1899042]]
[[-0.38703668]
 [ 0.9220643 ]
 [ 7.137138  ]]
[[0.44228253]]
[[-0.711877 ]
 [ 0.7023042]
 [ 7.8950286]]
[[1.8140976]]
[[-0.9414349 ]
 [ 0.33719477]
 [ 8.        ]]
[[0.44902456]]
[[-0.99740356]
 [-0.07201456]
 [ 8.        ]]
[[2.0815094]]
[[-0.88496554]
 [-0.46565655]
 [ 8.        ]]
[[0.2290068]]
[[-0.64587176]
 [-0.7634459 ]
 [ 7.6851087 ]]
[[1.9799621]]
[[-0.32564014]
 [-0.9454938 ]
 [ 7.4095182 ]]
[[-1.0297275]]
[[-4.3917000e-03]
 [-9.9999034e-01]
 [ 6.5459390e+00]]
[[2.971837]]
[[ 0.29590765]
 [-0.9552165 ]
 [ 6.0959463 ]]
[[2.9198341]]
[[ 0.55168426]
 [-0.83405304]
 [ 5.679534 

[[-0.9988835]]
[[ 0.1950371 ]
 [ 0.98079586]
 [-0.49291068]]
[[3.3592691]]
[[0.16835524]
 [0.9857264 ]
 [0.54268616]]
[[-1.6375474]]
[[0.11707433]
 [0.9931232 ]
 [1.0363489 ]]
[[-3.0092392]]
[[0.04327044]
 [0.9990634 ]
 [1.4811914 ]]
[[0.84271955]]
[[-0.07449204]
 [ 0.9972216 ]
 [ 2.3568969 ]]
[[-0.45502493]]
[[-0.22446005]
 [ 0.9744833 ]
 [ 3.0365593 ]]
[[1.7704954]]
[[-0.41508713]
 [ 0.90978163]
 [ 4.032996  ]]
[[-0.14480951]]
[[-0.61526275]
 [ 0.7883221 ]
 [ 4.693611  ]]
[[4.0174627]]
[[-0.80871356]
 [ 0.58820266]
 [ 5.5848527 ]]
[[-1.811938]]
[[-0.94237924]
 [ 0.33454645]
 [ 5.754214  ]]
[[1.2306463]]
[[-0.99949956]
 [ 0.03163272]
 [ 6.1897206 ]]
[[-2.1306896]]
[[-0.965345  ]
 [-0.26097703]
 [ 5.913445  ]]
[[-1.9015392]]
[[-0.85993284]
 [-0.5104072 ]
 [ 5.4324813 ]]
[[-0.05466375]]
[[-0.7054546 ]
 [-0.70875514]
 [ 5.0414762 ]]
[[1.9552903]]
[[-0.5166247 ]
 [-0.85621196]
 [ 4.8032036 ]]
[[4.6231112]]
[[-0.3144259 ]
 [-0.94928205]
 [ 4.4610443 ]]
[[-2.425771]]
[[-0.14686453]
 [-0.989

In [1]:
def render(self, mode='human'):
        if self.viewer is None:
            from gym.envs.classic_control import rendering
            self.viewer = rendering.Viewer(500, 500)
            self.viewer.set_bounds(-2.2, 2.2, -2.2, 2.2)
            rod = rendering.make_capsule(1, .2)
            rod.set_color(.8, .3, .3)
            self.pole_transform = rendering.Transform()
            rod.add_attr(self.pole_transform)
            self.viewer.add_geom(rod)
            axle = rendering.make_circle(.05)
            axle.set_color(0, 0, 0)
            self.viewer.add_geom(axle)
            fname = path.join(path.dirname(__file__), "assets/clockwise.png")
            self.img = rendering.Image(fname, 1., 1.)
            self.imgtrans = rendering.Transform()
            self.img.add_attr(self.imgtrans)

        self.viewer.add_onetime(self.img)
        self.pole_transform.set_rotation(self.state[0] + np.pi / 2)
        if self.last_u:
            self.imgtrans.scale = (-self.last_u / 2, np.abs(self.last_u) / 2)

        return self.viewer.render(return_rgb_array=mode == 'rgb_array')

In [4]:
# collect saved results
import numpy as np
from matplotlib import pyplot as plt
r1 = np.genfromtxt("InvertedPendulum_results.csv", delimiter=",")
all_results = [r1]
labels = ["REINFORCE"]

##############################################################
# Plotting Policy Gradient results below
##############################################################
def plot_results(all_results,labels):
    colors= plt.figure(figsize=(16,9))
    for i,(label,result) in enumerate(zip(labels,all_results)):
        plt.plot(np.arange(result.shapes[1]), np.mean(result,0),
                color=colors(i), linewidth=2, label=label)
        plt.fill_between(np.arange(len(result[0])),
                        np.mean(result,0)-np.std(result,0),
                        np.mean(result,0)+np.std(result,0),
                        alpha=0.25, color=colors(i))
    plt.ylabel('cumulative return')
    plt.xlabel('trainig iteration')
%matplotlib inline
fig=plot_results(all_results,labels)

AttributeError: 'numpy.ndarray' object has no attribute 'shapes'

<Figure size 1152x648 with 0 Axes>